-- ============================================================
-- Migration 010: Seed DUX + Lamino products from fanins.se
-- Project: Skandiva Tapetserarverkstad Stockholm
-- ============================================================

CREATE TABLE IF NOT EXISTS products (
  id text primary key,
  slug text unique not null,
  name text not null,
  designer text not null,
  model text not null,
  category text not null,
  category_name_swedish text not null,
  collection text not null default 'none',
  base_price numeric not null,
  description text not null,
  historical_context text,
  dimensions text,
  condition_grade text,
  provenance_crest_text text,
  stock_status text not null default 'i_lager',
  primary_image text not null,
  gallery_images jsonb default '[]'::jsonb,
  material_ids jsonb not null default '[]'::jsonb,
  before_image text,
  after_image text,
  featured boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS collection text NOT NULL DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS material_ids jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS products_collection_idx ON products(collection);

INSERT INTO products (
  id,
  slug,
  name,
  designer,
  model,
  category,
  category_name_swedish,
  collection,
  base_price,
  description,
  historical_context,
  dimensions,
  condition_grade,
  provenance_crest_text,
  stock_status,
  primary_image,
  gallery_images,
  material_ids,
  before_image,
  after_image,
  featured
)
VALUES
  (
    'fanins-dux-jetson-69-lader',
    'kuddsats-till-jetson-69-dux-i-exklusiv-lader',
    'KUDDSATS TILL JETSON 69 DUX i EXKLUSIVE LÄDER',
    'Bruno Mathsson',
    'Jetson 69',
    'Fatolj',
    'Fåtöljer',
    'dux',
    9825,
    'Kuddsats till Jetson 69 DUX i exklusivt läder med originalkänsla, noggrant anpassad för Bruno Mathssons klassiska form.',
    'Bruno Mathsson formgav Jetson 69 som en svensk möbelklassiker och den har återfått popularitet genom varsam restaurering.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Bruno Mathsson Jetson 69 renovering',
    'i_lager',
    '/IMG_0611.jpeg',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0611.jpeg',
    '/IMG_0611.jpeg',
    true
  ),
  (
    'fanins-dux-jetson-69-flax-canvas',
    'kuddsats-till-jetson-69-dux-flax-canvas',
    'Kuddsats till Jetson 69 Dux flax canvas',
    'Bruno Mathsson',
    'Jetson 69',
    'Fatolj',
    'Fåtöljer',
    'dux',
    6325,
    'Flax canvas-kudde anpassad för Jetson 69 DUX med ljus, elegant känsla och tydlig skandinavisk profil.',
    'Bruno Mathsson formgav Jetson 69 som en svensk möbelklassiker och den har återfått popularitet genom varsam restaurering.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Bruno Mathsson Jetson 69 renovering',
    'i_lager',
    '/IMG_0611.jpeg',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0611.jpeg',
    '/IMG_0611.jpeg',
    false
  ),
  (
    'fanins-dux-omkladsel-jetson-barande-vav',
    'omkladsel-jetson-omkladsel-av-barande-vav',
    'Omklädsel Jetson (omklädsel av bärande väv)',
    'Bruno Mathsson',
    'Jetson 69',
    'Fatolj',
    'Fåtöljer',
    'dux',
    5200,
    'Omklädsel av Jetson med bärande väv för bevarande av konstruktion, komfort och ursprunglig form.',
    'Bruno Mathsson formgav Jetson 69 som en svensk möbelklassiker och den har återfått popularitet genom varsam restaurering.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Bruno Mathsson Jetson 69 renovering',
    'i_lager',
    '/IMG_0611.jpeg',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0611.jpeg',
    '/IMG_0611.jpeg',
    false
  ),
  (
    'fanins-dux-pernilla-69-lader',
    'kuddsats-till-pernilla-69-lader',
    'Kuddsats till Pernilla 69 läder',
    'Bruno Mathsson',
    'Pernilla 69',
    'Fatolj',
    'Fåtöljer',
    'dux',
    23800,
    'Premiumkudde i läder för Pernilla 69 med noggrann passform och exklusiv finish.',
    'Bruno Mathsson formgav Pernilla 69 som en svensk möbelklassiker och den har återfått popularitet genom varsam restaurering.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Bruno Mathsson Pernilla 69 renovering',
    'i_lager',
    '/IMG_0611.jpeg',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0611.jpeg',
    '/IMG_0611.jpeg',
    true
  ),
  (
    'fanins-dux-pernilla-69-flax21',
    'kuddsats-till-pernilla-69-i-flax21-dux',
    'Kuddsats till Pernilla 69 i Flax21 Dux',
    'Bruno Mathsson',
    'Pernilla 69',
    'Fatolj',
    'Fåtöljer',
    'dux',
    11900,
    'Ljus och modern flax-kudde för Pernilla 69 som ger ett tidlöst och praktiskt uttryck.',
    'Bruno Mathsson formgav Pernilla 69 som en svensk möbelklassiker och den har återfått popularitet genom varsam restaurering.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Bruno Mathsson Pernilla 69 renovering',
    'i_lager',
    '/IMG_0611.jpeg',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0611.jpeg',
    '/IMG_0611.jpeg',
    false
  ),
  (
    'fanins-dux-pernilla-elmo-soft',
    'kuddsats-till-pernilla-dux-i-elmo-soft-lader',
    'Kuddsats till Pernilla DUX i ELMO Soft läder',
    'Bruno Mathsson',
    'Pernilla DUX',
    'Fatolj',
    'Fåtöljer',
    'dux',
    19900,
    'ELMO Soft kombinerar mjukhet och hållbarhet i en elegant, modern läderkudde för Pernilla DUX.',
    'Bruno Mathsson formgav Pernilla DUX som en svensk möbelklassiker och den har återfått popularitet genom varsam restaurering.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Bruno Mathsson Pernilla DUX renovering',
    'i_lager',
    '/IMG_0611.jpeg',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0611.jpeg',
    '/IMG_0611.jpeg',
    false
  ),
  (
    'fanins-lamino-omkladsel-fatolj',
    'omkladsel-av-lamino-fatolj',
    'Omklädsel av lamino fåtölj',
    'Yngve Ekström',
    'Lamino',
    'Fatolj',
    'Fåtöljer',
    'lamino',
    3900,
    'Specialiserad omklädsel av Lamino-fåtölj i premiumfårskinn, byggd för lång livslängd och klassisk estetik.',
    'Yngve Ekström formgav Lamino som ett svenskt designikoner och den förtjänar varsam restaurering med rätt material.',
    'Anpassad efter originalmodell och skick.',
    'Nyskick',
    'Skandiva — certifierad Yngve Ekström Lamino renovering',
    'i_lager',
    '/IMG_0948.png',
    '[]'::jsonb,
    '[]'::jsonb,
    '/IMG_0948.png',
    '/IMG_0948.png',
    true
  )
ON CONFLICT (id)
DO UPDATE SET
  slug = EXCLUDED.slug,
  name = EXCLUDED.name,
  designer = EXCLUDED.designer,
  model = EXCLUDED.model,
  category = EXCLUDED.category,
  category_name_swedish = EXCLUDED.category_name_swedish,
  collection = EXCLUDED.collection,
  base_price = EXCLUDED.base_price,
  description = EXCLUDED.description,
  historical_context = EXCLUDED.historical_context,
  dimensions = EXCLUDED.dimensions,
  condition_grade = EXCLUDED.condition_grade,
  provenance_crest_text = EXCLUDED.provenance_crest_text,
  stock_status = EXCLUDED.stock_status,
  primary_image = EXCLUDED.primary_image,
  gallery_images = EXCLUDED.gallery_images,
  material_ids = EXCLUDED.material_ids,
  before_image = EXCLUDED.before_image,
  after_image = EXCLUDED.after_image,
  featured = EXCLUDED.featured;
